In [23]:
import pandas as pd

In [12]:
tabela = pd.read_excel("/content/drive/MyDrive/Data/Vendas.xlsx")

In [17]:
tabela.head()

,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,2019-12-01,Iguatemi Campinas,Bermuda Estampa,1,169,169
1,2019-12-01,Iguatemi Esplanada,Bermuda Xadrez,1,155,155
2,2019-12-01,Norte Shopping,Bermuda,2,150,300
3,2019-12-01,Iguatemi Campinas,Bermuda Listrado,3,163,489
4,2019-12-01,Iguatemi Campinas,Bermuda Linho,3,195,585

In [18]:
#cálculo do faturamento total da empresa
faturamento_total = tabela["Valor Final"].sum()
faturamento_total

55895

In [16]:
#cálculo do faturamento por loja
faturamento_loja = tabela[["ID Loja", "Valor Final"]].groupby("ID Loja").sum()
faturamento_loja

                            Valor Final
ID Loja
Bourbon Shopping SP                4386
Center Shopping Uberlândia         2994
Iguatemi Campinas                 41720
Iguatemi Esplanada                 2473
Norte Shopping                     4322

In [25]:
#cálculo do faturamento por loja e filtrando por produto
faturamento_produto = tabela[["ID Loja", "Produto", "Valor Final"]].groupby(["ID Loja", "Produto"]).sum()
faturamento_produto

                                             Valor Final
ID Loja                    Produto
Bourbon Shopping SP        Bermuda                   750
                           Bermuda Estampa          1183
                           Bermuda Linho             195
                           Bermuda Listrado         1793
                           Bermuda Xadrez            465
Center Shopping Uberlândia Bermuda Estampa           338
                           Bermuda Linho             780
                           Bermuda Listrado          326
                           Bermuda Xadrez           1550
Iguatemi Campinas          Bermuda                  1200
                           Bermuda Estampa           845
                           Bermuda Linho            1170
                           Bermuda Liso            36581
                           Bermuda Listrado         1304
                           Bermuda Xadrez            620
Iguatemi Esplanada         Bermuda                   150
                           Bermuda Estampa           338
                           Bermuda Linho            1365
                           Bermuda Xadrez            620
Norte Shopping             Bermuda                  1350
                           Bermuda Estampa           845
                           Bermuda Linho             390
                           Bermuda Listrado          652
                           Bermuda Xadrez           1085

#O shopping Iguatemi Campinas, possui um produto chamado Bermuda Liso, que outros shoppings não possuem. Para aumentar as vendas da empresa, seria interessante tentar vender esse produto nos outros shoppings.#